### ISSUE TITLE
Can't install with Luarocks

### ISSUE THREAD

**Issue by chandimaei** [JorjBauer/lua-cyrussasl#4]
Hey, I tried to install this through with https://luarocks.org/ package manager. But it says 

fatal: remote error:
#0 90.96   The unauthenticated git protocol on port 9418 is no longer supported.
#0 90.96 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

As I further dug into this and found out that GitHub has updated their security measures and they no longer accept the git:// for package URL. Only HTTPS:// is allowed. As your Luarocks config file, it is still with the older version. I know you guys haven't worked with this for long now, but this is a bit important for me can you guys update this. I can add a PR if you want.

**Comment by JorjBauer** [comment]
Done! There haven't been any changes to this because the underlying project is stable. Thanks for the detailed issue report...
